### ISSUE TITLE
Question about multitenant hibernate configuration

### ISSUE THREAD

**Issue by shinank** [mdeinum/spring-utils#1]
Is spring-utils, particularly the multitenant for hibernate compatible with Spring 3.0.5?

Thanks.

**Comment by mdeinum** [comment]
It was initially developed for Spring 2.0 so it should work. You might need to get a bit older version as the recent trunk has been upgraded to newer spring versions. But you could give it a try.

**Comment by shinank** [comment]
Thanks! I did manage to get it working in my project.
